<?php

/**
 * @file
 * Main file of the module, implements basic module's functionality.
 */

/**
 * Implements hook_menu().
 */
function mysearch_menu() {
  $items['mysearch/%'] = array(
    'title' => 'Search',
    'page callback' => 'mysearch_searchpage',
    'page arguments' => array(1),
    'access arguments' => array('access mysearch'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function mysearch_permission() {
  return array(
    'access mysearch' => array(
      'title' => t('Access My Search'),
      'description' => t('Allows a user to access search results'),
    ),
  );
}


/**
 * Menu callback provides a simple list of nodes matching the search term.
 *
 * Example:
 * hitting the URL http://domain.com/mysearch/example will return a list of
 * links to nodes which have the word "example" in them.
 *
 * @param string $search_term
 *   Search term.
 *
 * @return string
 *   Rendered (html) search result.
 */
function mysearch_searchpage($search_term) {
  // Perform search query.
  $search_results = db_select('node', 'node')
    ->fields('node', array('nid', 'title'))
    ->condition('node.title', '%' . db_like($search_term) . '%', 'LIKE')
    ->addTag('node_access')
    ->execute();

  // Build array with result items.
  $items = array();
  foreach ($search_results as $search_result) {
    $items[] = l(
      $search_result->title,
      "node/{$search_result->nid}",
      array('attributes' => array('title' => $search_result->title))
    );
  }

  $title = t('Search for %searchterm', array('%searchterm' => $search_term));
  if ($items) {
    $output = array(
      'result' => array(
        '#theme' => 'item_list',
        '#items' => $items,
        '#title' => $title,
      ),
    );
  }
  // Display empty text in case when there are no result.
  else {
    $output = array(
      'title' => array(
        '#type' => 'item',
        '#markup' => $title,
      ),
      'result' => array(
        '#type' => 'item',
        '#markup' => t('No results found.'),
      ),
    );
  }

  return $output;
}
